print("Welcome to the String Manipulation Program!")
name=input("Enter your name: ")
print("Hello, " + name + "!")
res=name.find(name[0])
print("The first occurrence of  your name '" + name[0] + "' is at index: " + str(res))
print("Your name in uppercase: " + name.upper())
print("Your name in lowercase: " + name.lower())
print("Your name with leading and trailing spaces removed: '" + name.strip() + "'")
print("Your name repeated 3 times: " + name * 3)
print("The length of your name is: " + str(len(name)))
print("The first 3 characters of your name: " + name[:3])
print("The last 3 characters of your name: " + name[-3:])
print("Your name with 'a' replaced by 'o': " + name.replace('a', 'o'))
print("Is your name all alphabetic? " + str(name.isalpha()))
print("Is your name all uppercase? " + str(name.isupper()))
print("Is your name all lowercase? " + str(name.islower()))
print("Does your name start with 'J'? " + str(name.startswith('J')))
print("Does your name end with 'n'? " + str(name.endswith('n')))
print("Your name split into a list: " + str(name.split()))
for char in name:
    print(char)
print("Your name reversed: " + name[::-1])